Repository TomerFi/version-bumper-action, pull requests merged in 2022-10, with the labels that each got.

#33 docs: better community docs
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/linters/.markdown-lint.yml
  CONTRIBUTING.md
Labels: status: needs review, size: l, hacktoberfest-accepted

#35 chore: remove deprecated actions syntax
  action.sh
Labels: status: approved, size: s, hacktoberfest-accepted

#37 build(deps): bump tomerfi/version-bumper from 2.1.0 to 2.1.1
  Dockerfile
Labels: status: needs review, size: xs
